export PATH="/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/bin:/opt/aws/bin:/opt/aws/bin:/home/ec2-user/bin"
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="fintanmcevoy"
plugins=(git)
DISABLE_AUTO_UPDATE="true"
source $ZSH/oh-my-zsh.sh
export O_RUNNING='TRUE'
export TZ=GMT
export PATH=/home/fmcevoy/.pyenv/bin:$PATH
export PATH=~:~/Fmcevoy/:$PATH
stty erase '^?'

TERM='xterm-256color'

eval "$(pyenv init -)"
alias python='ipython'
alias nano='vim'
alias v='vim'
alias j='jrnl'
alias j1='jrnl -1'
alias je='jrnl -1 --edit'
alias t='tmux attach-session -t bash'
alias c='new_tmux_session'
alias grep='grep --color'
alias ls='ls --color'

alias wcc='cd ~/workspace/'
gdd() {
    grep -r -E "$1" .
}
}
ptest() {
    python -m py.test test/$1 -s -vv --pdb
}

bindkey -v
bindkey '^A' vi-beginning-of-line
bindkey '^E' vi-end-of-line
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

function zle-line-init zle-keymap-select {
    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/} $EPS1"
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1

SOCK="/tmp/ssh-agent-$USER-tmux"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]
then
    rm -f /tmp/ssh-agent-$USER-tmux
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi

t
