#!/bin/bash
rm ~/.zshrc
rm ~/.vimrc
rm ~/.jrnl_config
rm ~/workspaces/setup.cfg
rm ~/.gitconfig
rm ~/.tmux.conf
rm ~/.tmux_ssh_agent
rm ~/.config/git/excludes
sudo rm -r ~/.vim/*
sudo rm -r ~/.pyenv
sudo rm -r ~/.oh-my-zsh
